name: authentification
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.3.1
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/logo/
    - assets/images/splash_images/
    - assets/images/onbording_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/dashboard/
    - assets/images/profile_images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
